### ISSUE TITLE
Finish "additional circuit" on breadboard

### ISSUE THREAD

**Issue by dymnz** [dymnz/sEMG#1]

**Comment by dymnz** [comment]
@abb133aaa111 

Things to test:

#### 1. Frequency response 
* BW: 20~500Hz 
* LF-3dB: ~20Hz
* HF-3dB: ~500Hz

#### 2. DC level
* ~0V before level shifter
* ~2.5V after level shifter

#### 3. Output voltage swing
* Should be -2.5 ~ 0 ~ 2.5V before level shifter
* Should be 0 ~ 2.5 ~ 5V after level shifter

**Comment by dymnz** [comment]
@abb133aaa111 


Expected result:

https://docs.google.com/presentation/d/13LqZ7OEGJOKtB6LqreZgzk4dzq1huQg-WHFK5ndtOz4/edit#slide=id.g17ed01960b_0_34

**Comment by max2468tw** [comment]
[20170407.docx](https://github.com/dymnz/sEMG/files/907176/20170407.docx)
