### ISSUE TITLE
ADC reading interval swing

### ISSUE THREAD

**Issue by dymnz** [dymnz/sEMG#11]
### Interval between two consecutive ADC reading swing by  6 +- 1 microseconds, with 6 ~ 80% of the time.

* Caused by micros() call?
  * Check the interval between consecutive micros() call, should swing or have random peak based on previous test
* Effect of interval swing?
  * Ask teacher

### Example
![](https://raw.githubusercontent.com/dymnz/sEMG/master/ADC_Arduino/Testing/Results/ADC_Interval_Result/4000_fixed.png)

Relevant: https://github.com/LINPOYU/ultrasound/issues/3

**Comment by LINPOYU** [comment]
hihi~

**Comment by dymnz** [comment]
https://github.com/LINPOYU/ultrasound/issues/3
https://github.com/LINPOYU/ultrasound/issues/4

**Comment by dymnz** [comment]
### Probability of time interval between two consecutive ADC read
![](https://raw.githubusercontent.com/dymnz/sEMG/master/ADC_Arduino/Testing/Results/ADC_Interval_Result/ADCIntervalProb.png)
### Probability of time interval between two consecutive micros() call
![](https://raw.githubusercontent.com/dymnz/sEMG/master/ADC_Arduino/Testing/Results/ADC_Interval_Result/MircrosIntervalProb.png)

---
### Conclusion
micros() call cause the ADC read interval swing

**Comment by dymnz** [comment]
### Probability of time interval between two consecutive ADC read with 400us delay by naive delay
![](https://raw.githubusercontent.com/dymnz/sEMG/master/ADC_Arduino/Testing/Results/ADC_Interval_Result/ADCIntervalProb_delay400.png)
### Probability of time interval between two consecutive micros() call
![](https://raw.githubusercontent.com/dymnz/sEMG/master/ADC_Arduino/Testing/Results/ADC_Interval_Result/MircrosIntervalProb_delay400.png)

---
### Conclusion
?

**Comment by dymnz** [comment]
### Probability of time interval between two consecutive ADC read with 400us delay by delaymicroseconds()
![](https://raw.githubusercontent.com/dymnz/sEMG/master/ADC_Arduino/Testing/Results/ADC_Interval_Result/ADCIntervalProb_delay400_func.png)
### Probability of time interval between two consecutive micros() call
![](https://raw.githubusercontent.com/dymnz/sEMG/master/ADC_Arduino/Testing/Results/ADC_Interval_Result/MircrosIntervalProb_delay400_func.png)

---
### Conclusion
