### ISSUE TITLE
Force detection of static signal file on PC

### ISSUE THREAD

**Issue by dymnz** [dymnz/sEMG#15]
Given a sEMG signal, find a way to detect if force is used.

- [x] Signal files given

**Comment by dymnz** [comment]
@abb133aaa111 @max2468tw 
訊號在這裡 https://github.com/dymnz/sEMG/tree/master/Signals

### Usage
Please refer to [Signal plotting example](https://github.com/dymnz/sEMG/tree/master/ADC_NI_DAQ/Signal%20plotting%20example) for Matlab

**Comment by dymnz** [comment]
@abb133aaa111 @max2468tw 

你們星期五下午或星期六有空嗎? 我可以教你們怎麼用新電極和arduino讀取

**Comment by max2468tw** [comment]
星期六早上應該方便 可是要meeting
請問星期五晚上可以嗎?還是可能有些晚

**Comment by dymnz** [comment]
OK, 幾點?

**Comment by max2468tw** [comment]
做完電子實驗6. 假若晚餐後6.半方便嗎? 之後到晚上都沒什麼事!

**Comment by dymnz** [comment]
那星期五晚上七點好了

**Comment by abb133aaa111** [comment]
我可以

2017-05-17 13:52 GMT+08:00 Dymnz <notifications@github.com>:

**Comment by abb133aaa111** [comment]
我用內建的example blinkwithoutdelay出現這個結果
​

2017-05-17 13:52 GMT+08:00 Dymnz <notifications@github.com>:

**Comment by dymnz** [comment]
@abb133aaa111 
你從email傳的嗎?  看不到你的結果

**Comment by abb133aaa111** [comment]
對 那這樣呢
http://i.imgur.com/KdnjOpm.png
內建的example blinkwithoutdelay

2017-05-20 13:12 GMT+08:00 Dymnz <notifications@github.com>:

**Comment by dymnz** [comment]
這是有成功燒進去了. 只是你沒有改led pin, 所以看不出結果.
